import type { Metadata } from "next";
import "./globals.css";
import TapBar from "@/components/ui/TapBar";
import NavBarMobile from "@/components/ui/NavBarMobile";
import NavBarDesktop from "@/components/ui/NavBarDesktop";
import Header from "@/components/features/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="min-h-full flex flex-col">
        <Header />
        
        <NavBarMobile/>
        <NavBarDesktop/>
        {children}
        <TapBar/>
      
      </body>
    </html>
  );
}
