import type { Metadata } from "next";
import "./globals.css";
import TapBar from "@/components/features/TapBar";
import NavBarMobile from "@/components/features/NavBarMobile";
import NavBarDesktop from "@/components/features/NavBarDesktop";
import Footer from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="min-h-full flex flex-col bg-background">
        {/* <Header /> */}
        
        <NavBarMobile/>
        <NavBarDesktop/>
        {children}
        <TapBar/>
        <footer>
            <Footer />
        </footer>
      
      </body>
    </html>
  );
}
